module.exports = {
    MASTER_STATE_INIT: 0,
    MASTER_STATE_RUNNING: 1,
    MASTER_STATE_CLOSE: 2,

    WORKER_STATE_INIT: 0,
    WORKER_STATE_CREATED: 1,
    WORKER_STATE_ONLINE: 2,
    WORKER_STATE_LISTENING: 3,
    WORKER_STATE_CLOSE: 4,
    WORKER_STATE_DISCONNECT: 5,


    MSG_SHUTDOWN: 'workerMessageShutdown'
};